name: Build and Deploy Web App
on:
  push:
    branches:
      - main
jobs:
  hosting:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - uses: actions/checkout@v3

      # Install Flutter command
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version

      # Build Website
      - name: Build Website
        run: |
          flutter clean
          flutter pub get
          flutter build web
        working-directory: ./

      # Deploy Firebase Hosting
      - name: Deploy Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:todo-application-6414a
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./
